# Generated by Django 5.1.1 on 2024-10-21 00:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TurmaCadetes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turma', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserMilitar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('numerica', models.CharField(blank=True, max_length=20, null=True)),
                ('cargo', models.CharField(choices=[('Oficial_comandante', 'Oficial Comandante'), ('Oficial', 'Oficial'), ('Cadete', 'Cadete')], max_length=20)),
                ('permissao_anotar', models.BooleanField(default=False)),
                ('senha', models.CharField(max_length=255)),
                ('cadete_de_dia', models.BooleanField(default=False)),
                ('turma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='anotacao.turmacadetes')),
            ],
        ),
        migrations.CreateModel(
            name='ArquivoExportado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_arquivo', models.CharField(max_length=255)),
                ('data_exportacao', models.DateTimeField(auto_now_add=True)),
                ('arquivo', models.FileField(upload_to='exportacoes/')),
                ('exportado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anotacao.usermilitar')),
            ],
        ),
        migrations.CreateModel(
            name='Anotacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_anotacao', models.CharField(choices=[('positiva', 'Positiva'), ('negativa', 'Negativa')], max_length=10)),
                ('motivo', models.TextField()),
                ('status', models.CharField(default='notificada', max_length=20)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('despacho', models.CharField(blank=True, choices=[('pernoite', 'Pernoite'), ('revista', 'Revista'), ('outros', 'Outros')], max_length=10, null=True)),
                ('data_cumprimento', models.DateField(blank=True, null=True)),
                ('cadete_anotado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anotacao.usermilitar')),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='criado_por', to='anotacao.usermilitar')),
                ('despachado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='despachado_por', to='anotacao.usermilitar')),
            ],
        ),
    ]
